### ISSUE TITLE
Classification with multiple codewords/trigraphs cut off to left edge of page.

### ISSUE THREAD

**Issue by mitcand** [kprussing/secretx#16]
Using the example document, if we make a top-level that has multiple codewords/trigraphs, when printed next to paragraphs and footnotes they cut off to the left edge of the page.

`\addmarking{25}{(TI//AB-C/DEF-G/HI/JKL/NF)}{TOP IMPORTANCE//AB-C/DEF-G/HI/JKL/NF}`

Prints only the last few characters:

> G/HI/JKL/NF)

<img width="840" alt="Screen Shot 2022-04-05 at 12 08 39 PM" src="https://user-images.githubusercontent.com/103058821/161797992-04401b2b-65ef-4766-b9ed-822b35092d2d.png">

**Comment by kprussing** [comment]
Thanks for the feedback! I wasn't really sure how the qualifications would really play in since this started as a bit of a brain puzzle and hadn't really tried all the variations yet. Can you try out [this change](https://github.com/kprussing/secretx/pull/14#issuecomment-1064299906) and see if it helps? I'll be a offline for a bit while I deal with some personal issues, but I'm interested to see if that patch addresses this problem too (along with some others that I haven't had time to investigate).

**Comment by mitcand** [comment]
That does the trick! While I prefer the look of the classification off to the left, this functions much better with the longer caveats. Additionally, I really appreciate the ability to `\begin{unclassified} / \end{unclassified}` for each paragraph, it keeps the working document very clean.

<img width="815" alt="Screen Shot 2022-04-05 at 10 28 30 PM" src="https://user-images.githubusercontent.com/103058821/161883809-f0c58c95-6cc7-4361-9879-8f9273d38fae.png">
.
